- name: Ensure borg are installed
  pacman:
    name: borg
    state: present

- name: Check if /home/backups exists
  ansible.builtin.stat:
    path: /home/backups
  register: backups_dir

- name: Create /home/backups if it does not exist
  ansible.builtin.file:
    path: /home/backups
    state: directory
    owner: arch
    group: arch
    mode: '0755'
  when: not backups_dir.stat.exists

- name: Initialize Borg repository if not already initialized
  command: borg init -e keyfile /home/backups
  environment:
    BORG_PASSPHRASE: ""
  become: yes
  become_user: arch
  when: not backups_dir.stat.exists

- name: Install createlinks script
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - backuprepo
    - createlinks

- name: Install systemd timers
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - createlinks.timer
    - createlinks.service
    - backuprepo.timer
    - backuprepo.service

- name: Activate systemd timers
  service: name={{ item }} enabled=yes state=started
  with_items:
    - createlinks.timer
    - backuprepo.timer
