- name: Update pacman cache
  pacman:
    update_cache: yes

- name: Ensure archlinux-keyring is up-to-date
  pacman:
    name: archlinux-keyring
    state: latest

- name: Upgrade all packages
  pacman:
    upgrade: yes
    extra_args: --noconfirm

- name: Install essential tools
  pacman:
    name: vim,nano,tmux,htop,ncdu,rsync,vnstat,bc
    state: present

- name: Start and enable vnstatd
  service:
    name: vnstat
    enabled: yes
    state: started

- name: Start and enable auditd
  service:
    name: auditd
    enabled: yes
    state: started

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Add configure for gpg agent
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "StreamLocalBindUnlink yes"
    state: present

- name: Ensure SSH password authentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Set system timezone
  ansible.builtin.timezone:
    name: Asia/Shanghai
