- name: Install loong-api
  copy:
    src: "{{ lsrc_dir }}/loong-api"
    dest: "{{ ldest_dir }}/loong-api"
    owner: arch
    group: arch
    mode: '0755'

- name: Install index.html
  copy:
    src: ../../loong-status/new.html
    dest: /srv/http/status/html/new.html
    owner: http
    group: http
    mode: '0644'

- name: Create env file
  ansible.builtin.copy:
    dest: "{{ ldest_dir }}/.env"
    content: "DATABASE_URL=postgresql://{{ postgres_user }}:{{ postgres_password }}@localhost/archdb"
    owner: arch
    group: arch
    mode: '0644'

- name: Install systemd service
  template:
    src: "lapi.service.j2"
    dest: "/etc/systemd/system/lapi.service"
    owner: root
    group: root
    mode: '0644'

- name: Activate systemd service
  service:
    name: lapi.service
    enabled: yes
    state: started
