- name: Ensure nginx are installed
  pacman:
    name: nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Ensure Nginx is enabled
  systemd:
    name: nginx
    enabled: yes
