#!/usr/bin/python

"""
Generates a list of packages which can be rebuild depending on the already
rebuild packages in our staging repositories
"""

import argparse
import tempfile
import os

from pyalpm import Handle
import pyalpm

home_dir = os.path.expanduser("~")
cache_dir = os.path.join(home_dir, ".cache", "compare86")

def register_dbs(handle, reponames):
    repos = []

    for reponame in reponames:
        repo = handle.register_syncdb(reponame, pyalpm.SIG_DATABASE_OPTIONAL)
        repos.append(repo)

    return repos


def find_package_anywhere(handle, pkgname):
    for db in handle.get_syncdbs():
        pkg = db.get_pkg(pkgname)
        if pkg:
            return pkg

    return None


def can_rebuild(rebuild_packages, x86_handle, staging_handle, nocheck):
    rebuild_packages_set = set(rebuild_packages)

    def is_all_rebuild(depends):
        for pkg in depends:
            if pkg not in rebuild_packages_set:
                continue

            if not find_package_anywhere(staging_handle, pkg):
                return False

        return True

    can_rebuild_list = []
    for pkgname in rebuild_packages:
        # Already rebuild
        pkg = find_package_anywhere(staging_handle, pkgname)
        if pkg is not None:
            continue

        pkg = find_package_anywhere(x86_handle, pkgname)
        # No rebuild upstream
        if pkg is None:
            continue

        if is_all_rebuild(pkg.depends) and is_all_rebuild(pkg.makedepends) and (nocheck or is_all_rebuild(pkg.checkdepends)):
            can_rebuild_list.append(pkgname)

    return can_rebuild_list


def compare_repos(rebuild_packages, staging_handle):
    missing = []
    for pkgname in rebuild_packages:
        if find_package_anywhere(staging_handle, pkgname) is None:
            missing.append(pkgname)

    return missing

x86_handle = Handle(".", os.path.join(cache_dir, "x86"))
staging_handle = Handle(".", os.path.join(cache_dir, "loong"))

register_dbs(x86_handle, ["core-staging", "extra-staging"])
register_dbs(staging_handle, ["core-staging", "extra-staging"])

def printpkg(pkgname, indent_level=0):
    indent = "    " * indent_level
    pkgloong = find_package_anywhere(staging_handle, pkgname)
    pkgx86 = find_package_anywhere(x86_handle, pkgname)
    if (pkgloong is None) and (pkgx86 is not None):
        print(f"{indent}❌ {pkgname}")
    elif pkgx86 is None:
        pass
        #print(f"{indent}   {pkgname}")
    else:
        print(f"{indent}✅ {pkgname}")

def check(pkgname):
    pkg86 = find_package_anywhere(x86_handle, pkgname)
    if pkg86 is None:
        print("Not found in x86")
        return
    printpkg(pkgname)
    print("Depends:")
    for pkg in pkg86.depends:
        printpkg(pkg, 1)
    print("Make depends:")
    for pkg in pkg86.makedepends:
        printpkg(pkg, 1)
    print("Check depends:")
    for pkg in pkg86.checkdepends:
        printpkg(pkg, 1)

def main(filename, verify, nocheck, output_format):
    # Output of `genrebuild`.
    rebuild_packages = []
    packages = []

    with open(filename, 'r') as fp:
        rebuild_packages = fp.read().splitlines()

    if verify:
        packages = compare_repos(rebuild_packages, staging_handle)
    else:
        packages = can_rebuild(rebuild_packages, x86_handle, staging_handle, nocheck)

    if output_format == 'space':
        print(' '.join(packages))
    elif output_format == 'newline':
        print('\n'.join(packages))
    else:
        print('unsupported output format')

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
                        prog='canrebuild',
                        description='Returns packges which can be rebuild in the staging repositories')
    parser.add_argument('--file', type=str, default='python.lst', help='package list file')
    parser.add_argument('--package', type=str, help='package to check')
    parser.add_argument('--format', default='space', choices=['space', 'newline'])
    parser.add_argument('--nocheck', action=argparse.BooleanOptionalAction, help='ignore check dependencies')
    parser.add_argument('--verify', action=argparse.BooleanOptionalAction, help='compare staging versus stable packages')

    args = parser.parse_args()
    if args.package:
        check(args.package)
    else:
        main(args.file, args.verify, args.nocheck, args.format)
