#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: ${0##*/} <repo-name> <pkg-files>"
    exit 1
fi

TIER0=${TIER0:-""}

_remote_path=/srv/http/loongarch/archlinux/
REPO=$1
shift
ALLFILES="$@"

ALLSIG=()
for pkg in ${ALLFILES[@]}; do
    if [ ! -f $pkg.sig ]; then
        echo "Signing $pkg ..."
        gpg --detach-sign $pkg || exit 1
    fi
    ALLSIG+=($pkg.sig)
done

WORKDIR=$(mktemp -d)
cp ${ALLFILES[@]} $WORKDIR
echo ${ALLSIG[@]}
cp ${ALLSIG[@]} $WORKDIR

rsync -e ssh -p '--chmod=ug=rw,o=r' -c -h -L --progress --partial -y $WORKDIR/* $TIER0:$_remote_path/$REPO/os/loong64/ || exit 2
ssh -tt $TIER0"cd $_remote_path/$REPO/os/loong64/; repo-add -R $REPO.db.tar.gz ${ALLFILES[@]};"

rm -rf $WORKDIR
