#!/bin/bash

set -e

# DATABASE_CONF="database.json"
BUILDER="localhost"
BUILD_LIST="build_pkg"

while [[ $# -gt 0 ]]; do
    case "$1" in
        # --db|--database)
        #     DATABASE_CONF="$2"
        #     shift 2
        #     ;;
        --builder)
            BUILDER="$2"
            shift 2
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done
	
# Initialize database
echo "Stage 1: Initialize database"
python3 dbinit.py --bl black.lst
# Fetch packages that need to be built
echo "Stage 2: Compare packages and generate rebuild list"
python3 compare86.py -S -BEC --db -S
# Check for soname rebuilds
echo "Stage 3: Check for soname rebuilds"
python3 checksoname.py --db
# Generate build list
echo "Stage 4: Generate rebuild list"
python3 genrebuild --pkgdb  --dbpath /home/$USER/.cache/compare86/x86
# Clean up previous build repo
echo "Stage 5: Clean up previous build repo"
rm -rf /var/tmp/build-repo/
# Build packages
echo "Stage 6: Build packages using builder $BUILDER"
python3 autobuild.py --db --script ./1build.sh --builder $BUILDER
# Clean up
rm *.log
