#!/bin/bash

# Define variables
BACKUP_SOURCE_DIR="/srv/http/loongarch/archlinux"
BORG_REPO_DIR="/home/backups"
RETENTION_DAYS=30  # Retention period in days

# Create Borg backup with the current timestamp
su - arch -c "borg create -C zstd $BORG_REPO_DIR::repos-{now} $BACKUP_SOURCE_DIR"

# Prune old backups, keeping the last 30 daily backups
su - arch -c "borg prune --keep-daily=$RETENTION_DAYS $BORG_REPO_DIR"
